const cityList = [
  { label: "臺北市",code: 'TPE', value: "Taipei" },
  { label: "新北市",code: 'NWT', value: "NewTaipei" },
  { label: "桃園市",code: 'TYN', value: "Taoyuan" },
  { label: "臺中市",code: 'TXG', value: "Taichung" },
  { label: "臺南市",code: 'TNN', value: "Tainan" },
  { label: "高雄市",code: 'KHH', value: "Kaohsiung" },
  { label: "基隆市",code: 'KEL', value: "Keelung" },
  { label: "新竹市",code: 'HSZ', value: "Hsinchu" },
  { label: "新竹縣",code: 'HSZ', value: "HsinchuCounty" },
  { label: "苗栗縣",code: 'ZMI', value: "MiaoliCounty" },
  { label: "彰化縣",code: 'CHW', value: "ChanghuaCounty" },
  { label: "南投縣",code: 'NTC', value: "NantouCounty" },
  { label: "雲林縣",code: 'YUN', value: "YunlinCounty" },
  { label: "嘉義縣",code: 'CYI', value: "ChiayiCounty" },
  { label: "嘉義市",code: 'CYI', value: "Chiayi" },
  { label: "屏東縣",code: 'PIF', value: "PingtungCounty" },
  { label: "宜蘭縣",code: 'ILA', value: "YilanCounty" },
  { label: "花蓮縣",code: 'HUN', value: "HualienCounty" },
  { label: "臺東縣",code: 'TTT', value: "TaitungCounty" },
  { label: "金門縣",code: 'KNH', value: "KinmenCounty" },
  { label: "澎湖縣",code: 'PEH', value: "PenghuCounty" },
  { label: "連江縣",code: 'LNN', value: "LienchiangCounty" },
];

export default cityList;
